name: Tests

on:
  - push
  - pull_request

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Create Coverage File
        run: touch coverage.xml

      - name: Run unit tests with coverage
        run: docker-compose up --build --abort-on-container-exit

      - name: Send coverage report to codeclimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          set -ex
          wget -O reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x reporter
          ./reporter after-build